apiVersion: v1

kind: Service
metadata:
  name: notification-service-nodeport
spec:
  selector:
    app: notification-service
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 7000
      nodePort: 37000
    - name: https
      port: 443
      targetPort: 7001
      nodePort: 37001