version: "3.9"

networks:
  app-network:
    driver: bridge

services:
  # Services  

  user_service:
    image: user_service:local
    container_name: user_service
    build: 
        context: .
        dockerfile: ./src/UserService/Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - app-network

  notification_service:
    image: notification_service:local
    container_name: notification_service
    build: 
        context: .
        dockerfile: ./src/NotificationService/Dockerfile
    ports:
      - "7000:7000"
      - "7001:7001"
    networks:
      - app-network
