apiVersion: v1

kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000

    - name: https
      protocol: TCP
      port: 8001
      targetPort: 8001