apiVersion: v1

kind: Service
metadata:
  name: user-service-nodeport
spec:
  selector:
    app: user-service
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 38000
    - name: https
      port: 443
      targetPort: 8001
      nodePort: 38001