apiVersion: v1

kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: msg-port

    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: management